image: python:3.6-alpine

stages:
  - test

test_ingest_to_upload:
  stage: test
  script:
     - python -m unittest tests.test_ingest.TestRun.test_ss2_ingest_to_upload
  only:
    - dev
    - staging
  tags:
    - ingest-integration-tests

# TODO This tests submits bundles to the DSS, disabling this for now
#test_primary_submission:
#  stage: test
#  script:
#     - python -m unittest tests.test_ingest.TestRun.test_ss2_ingest_to_dss
#  only:
#    - dev
#    - integration
#    - staging

test_secondary_submission:
  stage: test
  script:
     - python -m unittest tests.test_ingest.TestRun.test_10x_analysis_run
  only:
    - dev
    - staging
  tags:
    - ingest-integration-tests

test_big_submission:
  stage: test
  script:
     - python -m unittest tests.test_ingest.TestRun.test_big_submission_run
  only:
    - dev
    - staging
  tags:
    - ingest-integration-tests

# TODO This tests submits bundles to the DSS, disabling this for now
#test_update_submission:
#  stage: test
#  script:
#     - python -m unittest tests.test_ingest.TestRun.test_updates_run
#  only:
#    - dev
#    - integration
#    - staging

# TODO This tests submits bundles to the DSS, disabling this for now
#test_add_new_bundle:
#  stage: test
#  script:
#    - python -m unittest tests.test_add_bundle.AddBundleTest.test_run
#  only:
#    - dev
#    - integration
#    - staging

before_script:
  - apk update
  - apk add  jq
  - apk add git
  - pip install awscli
  - pip install -r requirements.txt
  - hca
  - chmod a+x setup_ingest_config.sh && ./setup_ingest_config.sh
  - export DEPLOYMENT_ENV=$CI_COMMIT_REF_NAME
  - export DEPLOYMENT_STAGE=${DEPLOYMENT_ENV}
  - aws secretsmanager get-secret-value --region us-east-1 --secret-id ingest/${DEPLOYMENT_ENV}/gcp-credentials.json | jq -r .SecretString > gcp-credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd -P)/gcp-credentials.json
