variables:
  INTEGRATION_TEST_IMAGE_NAME: quay.io/ebi-ait/ingest-integration-tests:${CI_COMMIT_REF_NAME}
stages:
  - build
  - test

default:
  before_script:
    - export INGEST_API_JWT_AUDIENCE=https://data.humancellatlas.org/
    - export DEPLOYMENT_ENV=$CI_COMMIT_REF_NAME
    - export DEPLOYMENT_STAGE=${DEPLOYMENT_ENV}
    - export ARCHIVER_API_KEY=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id ingest/${DEPLOYMENT_ENV}/secrets --query SecretString --output text | jq -jr '.archiver_api_key')
    - export HCA_UTIL_ADMIN_ACCESS=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id hca/util/aws-access-keys --query SecretString --output text | jq -jr '.ADMIN_ACCESS_KEY')
    - export HCA_UTIL_ADMIN_SECRET=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id hca/util/aws-access-keys --query SecretString --output text | jq -jr '.ADMIN_SECRET_ACCESS_KEY')
    - export HCA_UTIL_ADMIN_PROFILE='test-hca-util-admin'
    - aws secretsmanager get-secret-value --region us-east-1 --secret-id ingest/${DEPLOYMENT_ENV}/gcp-credentials.json | jq -r .SecretString > gcp-credentials.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd -P)/gcp-credentials.json
  image: $INTEGRATION_TEST_IMAGE_NAME
  tags:
    - ingest-integration-tests

build:
  inherit:
    default: false
  image: quay.io/ebi-ait/ingest-base-images:docker_19.03.12
  services:
    - name: quay.io/ebi-ait/ingest-base-images:docker_19.03.12-dind
      alias: docker
  variables:
    # Variables for docker dind
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "prod")'
      changes:
        - Dockerfile
        - requirements.txt
        - tests/**/*
        - .gitlab-ci.yml
      when: always
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
  tags:
    - dind
  script:
    - echo $QUAY_PASSWORD | docker login quay.io -u $QUAY_USERNAME --password-stdin
    - docker build -t $INTEGRATION_TEST_IMAGE_NAME .
    - docker push $INTEGRATION_TEST_IMAGE_NAME

test_ingest_to_upload:
  stage: test
  script:
    - python -m unittest tests.test_ingest.TestRun.test_ingest_to_upload
  only:
    - dev
    - staging
    - prod


test_ingest_to_archives:
  stage: test
  script:
    - python -m unittest tests.test_ingest.TestRun.test_ingest_to_archives
  only:
    - dev
    - staging


test_ingest_to_terra:
  stage: test
  script:
    - python -m unittest tests.test_ingest.TestRun.test_ingest_to_terra
  only:
    - dev
    - staging


test_big_submission:
  stage: test
  script:
    - python -m unittest tests.test_ingest.TestRun.test_big_submission_run
  only:
    - dev
    - staging

test_bulk_update:
  stage: test
  script:
    - python -m unittest tests.test_ingest.TestRun.test_bulk_update
  only:
    - dev
    - staging
    - prod

test_direct_archiving:
  stage: test
  script:
    - python -m unittest tests.test_ingest.TestRun.test_direct_archiving
  only:
    - dev
    - staging
